@base_url = http://127.0.0.1:8000/api

### get mission by id
# @prompt mission_id Mission ID
GET  {{base_url}}/view/{{mission_id}}
Content-Type: application/json


### get missions with name
# @prompt name Name to Search
GET  {{base_url}}/view/gets?name={{name}}
Content-Type: application/json


### get missions with name and status
# @prompt name Name to Search
# @prompt status Status to Search
GET  {{base_url}}/view/gets?name={{name}}&status={{status}}
Content-Type: application/json


### get mission crew
# @prompt mission_id Mission ID
GET  {{base_url}}/view/crew/{{mission_id}}
Content-Type: application/json